---
title: ashwinikumarkulkarni.github.io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
Current: |-
  Research Scientist
  Prof. Konopka Lab
  Department of Neuroscience
  UT Southwestern Medical Center
  Dallas, TX
