#-------------------------------
# General Site Settings

title: Ashwinikumar Kulkarni
logo: logo.png
email: Ashwinikumar.Kulkarni<br>@UTSouthwestern.edu
phone: (214) 648-5138
address: UT Southwestern, ND4.300 <br> 6001 Forest Park, Road <br> Dallas, TX. 75390

menu:
- {name: About, link: '/about/'}
- {name: Publications, link: '/blog/'}
# - {name: Portfolio, link: '/portfolio/'}
- {name: Contact, link: '/contact/'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

# disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Ashwinikumar <br> Kulkarni <br> Ph.D.


social:
# - {icon: "ti-facebook", link: "#"}
# - {icon: "ti-instagram", link: "#"}
# - {icon: "ti-dribbble", link: "#"}
- {icon: "ti-github", link: "#"}
- {icon: "ti-twitter", link: "#"}
- {icon: "ti-linkedin", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  I am a research scientist at the Prof. Konopka Lab, Department of Neuroscience, UT Southwestern Medical Center. Using next-generation sequencing at single cell resolutions coupled with computational and machine-learning approaches, I am studying the complex gene regulatory networks to identify genomic signatures involved in neurodevelopmental diseases, sleep and circadian regulation.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Transcriptomics & Genomics"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title : "Neurodevelopmetal Diseases"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title : "Sleep & Circadian Regulation"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
# team:
  # - title : "Jack Schenziwe"
    # image : "assets/images/team/member-1.png"
    # designation : "Project Manager"

  # - title : "Julias Carlie"
    # image : "assets/images/team/member-2.png"
    # designation : "Web Developer"

  # - title : "John Doe"
    # image : "assets/images/team/member-3.png"
    # designation : "Designer"


#-------------------------------
# Skills Section

# skills-title: Skills
# skills:
# - {name: Web Design, color: '#fdb157', value: '90%'}
# - {name: Logo Design, color: '#9473e6', value: '60%'}
# - {name: After Effects, color: '#bdecf6', value: '80%'}
# - {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
# - {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
# - {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
# - {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}
- {name: Research Scientist, icon: 'icon-2.png', date: 'Mar 2016 - Till date', organization: 'UT Southwestern'}
- {name: Graduate Research Assistant, icon: 'icon-2.png', date: 'Mar 2016 - Till date', organization: 'UT Southwestern'}
- {name: Research Assistant II (Computational Biology), icon: 'icon-2.png', date: 'Mar 2016 - Till date', organization: 'UT Southwestern'}
- {name: Executive (Research & Development), icon: 'icon-2.png', date: 'Mar 2016 - Till date', organization: 'UT Southwestern'}
- {name: Research Trainee, icon: 'icon-2.png', date: 'Mar 2016 - Till date', organization: 'UT Southwestern'}
- {name: Research Associate cum Faculty, icon: 'icon-2.png', date: 'Mar 2016 - Till date', organization: 'UT Southwestern'}
# - {name: Research, icon: 'icon-3.png', date: 'Mar 2016 - Till date', organization: 'UT Southwestern'}
# - {name: Research Scientist, icon: 'icon-1.png', date: 'Mar 2016 - Till date', organization: 'UT Southwestern'}

#-------------------------------
# Education Section

education-title: Education
education:
# - {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
# - {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
# - {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
# - {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}
- {name: Ph.D. (Computational Biology), date: '2015', organization: 'University of Texas at Dallas, USA'}
- {name: M.S. (Molecular & Cell Biology), date: '2011', organization: 'University of Texas at Dallas, USA'}
- {name: M.Sc. (Biotechnology), date: '2005', organization: 'Nagpur University, India'}
- {name: B.Sc. (Chemistry), date: '2003', organization: 'Amravati University, India'}

#-------------------------------
# Services Section
#
# services-title: Services
# services:
# - {
#     name: UI Design,
#     icon: ti-palette,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: # Add true to select section
#   }
# - {
#     name: UX Design,
#     icon: ti-vector,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: true # Add true to select section
#   }
# - {
#     name: Interaction Design,
#     icon: ti-panel,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: # Add true to select section
#   }


#-------------------------------
# Portfolio (Section and Page)

# # Portfolio Home Section
# portfolio-home-items:
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
#
#   - image : "assets/images/portfolio/item-2.png"
#     url: "#"
#
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
#
#   - image : "assets/images/portfolio/item-4.png"
#     url: "#"
#
#   - image : "assets/images/portfolio/item-5.png"
#     url: "#"


# Portfolio Page
# portfolio-label:
# - {
#     title : "UI/UX Design",
#     type : "design"
#   }
# - {
#     title : "BRANDING",
#     type : "branding"
#   }
# - {
#     title : "ILLUSTRATION",
#     type : "illustration"
#   }
#
# portfolio-items:
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#      - type: "design"
#      - type: "illustration"
#
#   - image : "assets/images/portfolio/item-2.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"
#
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"
#
#   - image : "assets/images/portfolio/item-6.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "branding"
#
#   - image : "assets/images/portfolio/item-8.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"
#
#   - image : "assets/images/portfolio/item-5.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"
#
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "illustration"
#       - type: "branding"
#
#   - image : "assets/images/portfolio/item-7.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"


#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation : "CEO, Funder"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
#
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
#
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section
#
# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: Ashwinikumar.Kulkarni@UTSouthwestern.edu
